title: JWilbs
description: Personal Site for anything Data Science, Statistics, etc.

url: http://jwilber.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About Me
   url: /about
 - title: Contact
   url: /contact

social:
   github: jwilber
   twitter: 
   facebook: 
   email: j.wilber92@gmail.com

google_analytics: ""
